import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const tacticSans = localFont({
  src: "../public/fonts/TacticSans-Bld.woff2",
  variable: "--font-tactic-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={tacticSans.variable}>{children}</body>
    </html>
  );
}
