import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/presentation/components";
import { Rubik } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const rubik = Rubik();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
